### ISSUE TITLE
Construção das requisições dos projetos dentro do strateegia

### ISSUE THREAD

**Issue by silvercent011** [silvercent011/TramoiaAPI#6]
# ATENÇÃO NA TAREFA

- Criar as requisições que vão tratar dos projetos do strateegia
- Obter todos os projetos do usuário e armazenar no banco de dados
- Ter **atenção** aos schemas da API e na reutilização e manutenção de dados
- Não esquecer de documentar todo o código e de dar os commits certos na branch
- Mover os cards no GitHub Projects
## Task de documentação
- Abrir a aba Wiki do GitHub e escrever uma nova página com todos os detalhes das implementações feitas na API e no Banco de dados

**Comment by BrunoMSts** [comment]
Feito 👍
